# This GitHub workflow validates Bundle config (ML resource config and more)
# defined under mlops_demo_aws/databricks-resources/*
# and mlops_demo_aws/bundle.yml, when PRs are merged into the main branch
name: Bundle validation for mlops-demo-aws

on:
  workflow_dispatch:
  pull_request_target:

defaults:
  run:
    working-directory: ./mlops_demo_aws/

env:
  STAGING_WORKSPACE_TOKEN: ${{ secrets.STAGING_WORKSPACE_TOKEN }}
  PROD_WORKSPACE_TOKEN: ${{ secrets.PROD_WORKSPACE_TOKEN }}

jobs:
  staging:
    permissions: write-all
    concurrency: mlops-demo-aws-staging-bundle-job
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: install databricks bundle
        run: |
          ls
          sudo chmod +x ../scripts/install.sh
          echo "permission modified"
          sudo ../scripts/install.sh
        shell: bash
      - name: Validate Bundle For Staging Environment
        id: validate
        env:
          DATABRICKS_TOKEN: ${{ env.STAGING_WORKSPACE_TOKEN }}
        run: |
          databricks bundle validate -e staging > ../validate_output.txt
      - name: Create Comment with Bundle Configuration
        uses: actions/github-script@v6
        id: comment
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const fs = require('fs');
            const fileContents = fs.readFileSync('validate_output.txt', 'utf8');
            const output = `#### Bundle Staging Config Validated 🖌
            <details><summary>Staging Validation Output</summary>

            \`\`\`\n
            ${fileContents}
            \`\`\`

            </details>`

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

  prod:
    permissions: write-all
    concurrency: mlops-demo-aws-prod-bundle-job
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - uses: databricks/setup-cli@main
      - name: Validate Bundle For Prod Environment
        id: validate
        env:
          DATABRICKS_TOKEN: ${{ env.PROD_WORKSPACE_TOKEN }}
        run: |
          databricks bundle validate -e prod > ../validate_output.txt
      - name: Create Comment with Bundle Configuration
        uses: actions/github-script@v6
        id: comment
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const fs = require('fs');
            const fileContents = fs.readFileSync('validate_output.txt', 'utf8');
            const output = `#### Bundle Prod Config Validated 🖌
            <details><summary>Prod Validation Output</summary>

            \`\`\`\n
            ${fileContents}
            \`\`\`

            </details>`

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
