name: trigger tests in model serving and wait for result
on:
  workflow_dispatch:
    inputs:
      env:
        type: string
        required: true
      modelName:
        type: string
        required: true
      modelVersion:
        type: string
        required: true
      deploymentMode:
        type: string
        required: true

jobs:
  trigger-model-serving-and-wait:
    runs-on: ubuntu-latest
    steps:
      - name: trigger model serving and wait for the result
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: s-udhaya #owner name of target repo
          repo: mlops-demo-aws #target repo name
          github_token: ${{ secrets.GH_TOKEN }} #token with write access of target repo
          workflow_file_name: mlops-demo-aws-deploy-model-serving-dispatch-staging.yml #github.yml filename in target repo
          ref: main #branch name of target repo
          propagate_failure: true
          #client payload -> input parameters for target workflow
          client_payload: '{"modelName": "${{ github.event.inputs.modelName }}", "modelVersion": "${{ github.event.inputs.modelVersion }}", "deploymentMode": "${{ github.event.inputs.deploymentMode }}"}'